name: Python application

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --max-complexity=10 --max-line-length=127 --show-source --statistics
      - name: Measure complexity with Xenon
        run: |
          poetry run xenon --max-absolute A --max-modules A --max-average A path soil-moisture-sensory
      - name: Test with PyTest and generate coverage.xml
        run: |
          poetry run coverage run -m pytest && poetry run coverage xml coverage.xml
